---
title: 'Visualization exercise: more ggplot2 charttypes'
author: Mahmood Alsawad
date: '2024-04-03'
slug: []
categories: []
tags: []
description: ~
---

## Scatterplot chart with regression line
Using the Loess curve method

```{r problem_1_data,include=FALSE}

#####DO NOT MODIFY THIS CHUNK
library(tidyverse)

set.seed(12345)
var1<-runif(50,0,10)
set.seed(12345)
var2<-var1+rnorm(50,5,2)
set.seed(12345)
var3<- var1*(-rnorm(50,1,.2))

dat1<-tibble(var1,var2,var3)


```

```{r problem_1,echo=FALSE,message=FALSE}

####Make sure you install any necessary libraries
library(GGally)

ggplot(dat1, aes(x=var1, y=var2)) +
  geom_point()+
  geom_smooth()+
  labs(x="Variable 1", y="Variable2")

####PUT YOUR CODE HERE
```

## Scatterplot matrix
using the `ggpairs()` function from the `ggally` package.

```{r problem_2_data,include=FALSE}

#####DO NOT MODIFY THIS CHUNK

set.seed(10)
var1<-runif(50,0,10)
set.seed(10)
var2<-var1+rnorm(50,5,2)
set.seed(10)
var3<- var1*(-rnorm(50,1,.2))

dat2<-tibble(var1,var2,var3)


```


```{r solution_p2,echo=FALSE,message=FALSE}

####Make sure you load any necessary libraries
####PUT YOUR CODE HERE
library(ggcorrplot)
library(ggthemes)

my_scatter<-function(data,mapping){
  ggplot(data=data,mapping=mapping)+
    geom_jitter(color="orange")
}


my_density<-function(data,mapping){
  ggplot(data=data,mapping=mapping)+
    geom_density(fill="blue")
}

ggpairs(dat2,
        lower=list(continuous=my_scatter),
        diag=list(continuous=my_density))

```

## Shaded correlation matrix
using `ggcorrplot()`

```{r problem_3_data,include=FALSE}

#####DO NOT MODIFY THIS CHUNK

set.seed(12)
var1<-runif(50,0,10)
set.seed(12)
var2<-var1+rnorm(50,5,2)
set.seed(12)
var3<- var1*(-rnorm(50,1,.2))

dat3<-tibble(var1,var2,var3)

```

```{r problem3,echo=FALSE}

####Make sure you load any necessary libraries

####PUT YOUR CODE HERE

dat3_cor_tbl <-cor(dat3, use="complete.obs")

ggcorrplot(dat3_cor_tbl, type="lower", 
           title="Correlations", 
           ggtheme=theme_bw()
           )


```

## Cleveland dot plot

```{r problem_4_data,include=FALSE}

#####DO NOT MODIFY THIS CHUNK

set.seed(5678)
var1<-rnorm(10,25,5)
names<-letters[1:10]

dat4<-tibble(names,var1)


```

```{r problem_4,echo=FALSE}


####Make sure you load any necessary libraries

####PUT YOUR CODE HERE

ggplot(dat4, aes(x=var1,y=reorder(names,var1)))+
  geom_point(size = 5)+
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_line(linetype = "dotted", color = "red")
        )+
  labs(x="Variable 1", y ="")

```

## Lollipop plot
using `geom_piont()` and `geom_segment()`

```{r problem_5_data,include=FALSE}

#####DO NOT MODIFY THIS CHUNK

set.seed(13)
var1<-rnorm(10,25,5)
names<-letters[1:10]

dat5<-tibble(names,var1)


```

```{r problem_5,echo=FALSE}


####Make sure you load any necessary libraries

ggplot(dat5, aes(x = reorder(names, var1), y = var1))+
  geom_point(color = "#006400", size = 3)+
  geom_segment(aes(x = names, xend = names, y=0, yend=var1), color = "#006400")+
  theme(axis.text.x=element_text(angle=90))

```

## (Filled) Line chart
using `geom_area()`

```{r problem_6_data,include=FALSE}

#####DO NOT MODIFY THIS CHUNK

set.seed(8)
fiction<-tibble(Genre=rep("Fiction",5),Time=seq(1:5),Total=sample(1:10,5))
set.seed(7)
biography<-tibble(Genre=rep("Biography",5),Time=seq(1:5),Total=sample(1:10,5))
set.seed(9)
mystery<-tibble(Genre=rep("Mystery",5),Time=seq(1:5),Total=sample(1:10,5))

books_checked_out<-bind_rows(fiction,biography,mystery)
```

```{r problem_6,echo=FALSE}


####Make sure you load any necessary libraries

####PUT YOUR CODE HERE

ggplot(books_checked_out, aes(x = Time, y = Total, fill = Genre)) +
  geom_area()

```

## Dumbbell chart
using `geom_dumbbell()` from the `ggalt` package.

```{r problem_7_data,include=FALSE, message=FALSE, warning=FALSE}

#####DO NOT MODIFY THIS CHUNK

books_checked_out2 <- books_checked_out %>%
  filter(Time==1 | Time==5) %>%
  pivot_wider(names_from = Time,values_from=Total) %>%
  rename(Time1=`1`,Time5=`5`)

```
   
```{r,problem_7,echo=FALSE,message=FALSE, warning=FALSE}   


####Make sure you load any necessary libraries

####PUT YOUR CODE HERE

library(ggalt)

books_checked_out2 <- books_checked_out %>%
  filter(Time==1 | Time==5) %>%
  pivot_wider(names_from = Time,values_from=Total) %>%
  rename(Time1=`1`,Time5=`5`)

ggplot(books_checked_out2,
       aes(y=reorder(Genre,Time5),
           x=Time1,
           xend=Time5))+
  geom_dumbbell(colour_x = "red",
                colour_xend = "purple",
                size_x = 3,
                size_xend = 3) +
  labs(x = "", y = "Genre")

```

## Pie chart

```{r, problem_8_data,include=FALSE}

#####DO NOT MODIFY THIS CHUNK

pie_dat<-c(1,2,3,4,5)
```

```{r, problem_8,echo=FALSE}


###HINT: check the Help file for pie to see how to specify the color to the my_color palette

library(RColorBrewer)

my_color<-brewer.pal(5,"Spectral")

####Make sure you load any necessary libraries

####PUT YOUR CODE HERE
pie(pie_dat, col = my_color)


```

